service: project-bravo # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128 # set the maximum memory of the Lambdas in Megabytes
  timeout: 10 # the timeout is 10 seconds (default is 6 seconds)
  stage: ${opt:stage,'dev'} # setting the env stage to dev, this will be visible in the routes
  # stage: ${self:custom.secrets.NODE_ENV}
  region: us-east-1

    # environment:
  # NODE_ENV: ${self:custom.secrets.NODE_ENV}

package:
  individually: true
  exclude:
    - .git/**


custom:
  serverless-offline:
    port: 3001
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true


functions:
  - ${file(./src/endpoints/user.yml)}

plugins:
  - serverless-webpack
  - serverless-apigw-binary
  - serverless-domain-manager
  - serverless-offline # has to be the last one
